os:
- linux
sudo: false
language: python
python:
- "2.7"
install: pip install tox-travis
script: tox

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c "CREATE DATABASE travicidb;" -U postgres


after_success:
  - coveralls
  - codecov
